In [ ]:
###load the npz file 

In [6]:
import numpy as np

# Load dig_mnist dataset
dig_mnist_data = np.load(r'C:\Users\SONY\Desktop\kannada\Dig_MNIST\X_dig_MNIST.npz')
dig_mnist_images = dig_mnist_data['arr_0']
dig_mnist_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Dig_MNIST\y_dig_MNIST.npz')
dig_mnist_labels = dig_mnist_labels['arr_0']

# Load kannda_mnist dataset
kannda_mnist_train_data = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\X_kannada_MNIST_test.npz')
kannda_mnist_train_images = kannda_mnist_train_data['arr_0']
kannda_mnist_train_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\X_kannada_MNIST_train.npz')
kannda_mnist_train_labels = kannda_mnist_train_labels['arr_0']

kannda_mnist_test_data = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\y_kannada_MNIST_test.npz')
kannda_mnist_test_images = kannda_mnist_test_data['arr_0']
kannda_mnist_test_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\y_kannada_MNIST_train.npz')
kannda_mnist_test_labels = kannda_mnist_test_labels['arr_0']


In [ ]:
## reshape the data

In [9]:
import numpy as np
from sklearn.decomposition import PCA

# Load dig_mnist dataset
dig_mnist_data = np.load(r'C:\Users\SONY\Desktop\kannada\Dig_MNIST\X_dig_MNIST.npz')
dig_mnist_images = dig_mnist_data['arr_0']
dig_mnist_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Dig_MNIST\y_dig_MNIST.npz')
dig_mnist_labels = dig_mnist_labels['arr_0']

# Load kannda_mnist dataset
kannda_mnist_train_data = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\X_kannada_MNIST_train.npz')
kannda_mnist_train_images = kannda_mnist_train_data['arr_0']
kannda_mnist_train_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\y_kannada_MNIST_train.npz')
kannda_mnist_train_labels = kannda_mnist_train_labels['arr_0']

kannda_mnist_test_data = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\X_kannada_MNIST_test.npz')
kannda_mnist_test_images = kannda_mnist_test_data['arr_0']
kannda_mnist_test_labels = np.load(r'C:\Users\SONY\Desktop\kannada\Kannada_MNIST\y_kannada_MNIST_test.npz')
kannda_mnist_test_labels = kannda_mnist_test_labels['arr_0']

# Reshape the images to 2D arrays (flatten from 28x28 to 784 dimensions)
dig_mnist_images = dig_mnist_images.reshape((dig_mnist_images.shape[0], 28*28))
kannda_mnist_train_images = kannda_mnist_train_images.reshape((kannda_mnist_train_images.shape[0], 28*28))

# Perform PCA with 10 components
pca = PCA(n_components=10)
dig_mnist_images_pca = pca.fit_transform(dig_mnist_images)
kannda_mnist_train_images_pca = pca.transform(kannda_mnist_train_images)

# Reshape the test images to 2D arrays (flatten from 28x28 to 784 dimensions)
kannda_mnist_test_images = kannda_mnist_test_images.reshape((kannda_mnist_test_images.shape[0], 28*28))

# Perform PCA transformation on test images
kannda_mnist_test_images_pca = pca.transform(kannda_mnist_test_images)

# Print the shapes of the transformed images
print("Shape of dig_mnist images (PCA):", dig_mnist_images_pca.shape)
print("Shape of kannda_mnist train images (PCA):", kannda_mnist_train_images_pca.shape)
print("Shape of kannda_mnist test images (PCA):", kannda_mnist_test_images_pca.shape)


Shape of dig_mnist images (PCA): (10240, 10)
Shape of kannda_mnist train images (PCA): (60000, 10)
Shape of kannda_mnist test images (PCA): (10000, 10)


In [ ]:
# descsion tree

In [25]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Create a Decision Tree classifier
dt_classifier = DecisionTreeClassifier()

# Fit the classifier to the training data
dt_classifier.fit(X_train, y_train)

# Make predictions on the test data
dt_predictions = dt_classifier.predict(X_test)

# Calculate the accuracy of the classifier
dt_accuracy = accuracy_score(y_test, dt_predictions)
print("Decision Tree Accuracy:", dt_accuracy)


Decision Tree Accuracy: 0.7625


In [ ]:
# Random forest

In [11]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Create a Random Forest classifier
rf_classifier = RandomForestClassifier()

# Fit the classifier to the training data
rf_classifier.fit(X_train, y_train)

# Make predictions on the test data
rf_predictions = rf_classifier.predict(X_test)

# Calculate the accuracy of the classifier
rf_accuracy = accuracy_score(y_test, rf_predictions)
print("Random Forest Accuracy:", rf_accuracy)


Random Forest Accuracy: 0.8601


In [ ]:
# Naive Bayes Model

In [12]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Create a Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()

# Fit the classifier to the training data
nb_classifier.fit(X_train, y_train)

# Make predictions on the test data
nb_predictions = nb_classifier.predict(X_test)

# Calculate the accuracy of the classifier
nb_accuracy = accuracy_score(y_test, nb_predictions)
print("Naive Bayes Accuracy:", nb_accuracy)


Naive Bayes Accuracy: 0.7687


In [ ]:
##K-NN Classifier

In [13]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Create a K-NN classifier
knn_classifier = KNeighborsClassifier()

# Fit the classifier to the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
knn_predictions = knn_classifier.predict(X_test)

# Calculate the accuracy of the classifier
knn_accuracy = accuracy_score(y_test, knn_predictions)
print("K-NN Accuracy:", knn_accuracy)


K-NN Accuracy: 0.8609


In [ ]:
##SVM

In [14]:
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Create an SVM classifier
svm_classifier = SVC()

# Fit the classifier to the training data
svm_classifier.fit(X_train, y_train)

# Make predictions on the test data
svm_predictions = svm_classifier.predict(X_test)

# Calculate the accuracy of the classifier
svm_accuracy = accuracy_score(y_test, svm_predictions)
print("SVM Accuracy:", svm_accuracy)


SVM Accuracy: 0.8788


In [15]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Load the transformed training and test images
X_train = kannda_mnist_train_images_pca
y_train = kannda_mnist_train_labels
X_test = kannda_mnist_test_images_pca
y_test = kannda_mnist_test_labels

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)
dt_predictions = dt_classifier.predict(X_test)

# Random Forest Classifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

# Naive Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
nb_predictions = nb_classifier.predict(X_test)

# K-NN Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)
knn_predictions = knn_classifier.predict(X_test)

# SVM Classifier
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train, y_train)
svm_predictions = svm_classifier.predict(X_test)

# Calculate metrics for each classifier
classifiers = {
    'Decision Tree': dt_predictions,
    'Random Forest': rf_predictions,
    'Naive Bayes': nb_predictions,
    'K-NN': knn_predictions,
    'SVM': svm_predictions
}

for classifier, predictions in classifiers.items():
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted')
    recall = recall_score(y_test, predictions, average='weighted')
    f1 = f1_score(y_test, predictions, average='weighted')
    confusion_mat = confusion_matrix(y_test, predictions)
    roc_auc = roc_auc_score(y_test, svm_classifier.predict_proba(X_test), multi_class='ovr')
    
    print(f"Metrics for {classifier}:")
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("Confusion Matrix:")
    print(confusion_mat)
    print("ROC-AUC:", roc_auc)
    print("-------------------------")


Metrics for Decision Tree:
Accuracy: 0.7612
Precision: 0.7628635882097122
Recall: 0.7612
F1-Score: 0.7605437501761914
Confusion Matrix:
[[650 204   7  36  23   7   7  14  29  23]
 [113 745   8  31  37  15  13   8  12  18]
 [  5   9 938   6   4  27   3   2   3   3]
 [ 32  43   4 756  40  36  20  50   6  13]
 [ 10  22   2  51 747  87  13  15  30  23]
 [ 12  28  10  18 196 688   4   9  27   8]
 [  6  25   7  39  32  19 734 114   5  19]
 [ 33  29   4  34  24   7 214 613   5  37]
 [ 47  18  11   3  13  14   8   7 849  30]
 [ 15  18   0   3  16   1   5   9  41 892]]
ROC-AUC: 0.9907093000000001
-------------------------
Metrics for Random Forest:
Accuracy: 0.8609
Precision: 0.8648045879319091
Recall: 0.8609
F1-Score: 0.8606479520653453
Confusion Matrix:
[[754 183   0  29  10   0   1   8   8   7]
 [ 52 893   0  22  16   6   1   2   3   5]
 [  1   6 979   1   0  10   1   1   0   1]
 [ 17  12   3 887  28  23  10  19   1   0]
 [  1  12   0  41 889  33   4   6   9   5]
 [  6  14   1  11 176 775   

In [21]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Perform PCA with the given component size
pca = PCA(n_components=15)
X_train_pca = pca.fit_transform(kannda_mnist_train_images)
X_test_pca = pca.transform(kannda_mnist_test_images)

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train_pca, y_train)
dt_predictions = dt_classifier.predict(X_test_pca)

# Random Forest Classifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train_pca, y_train)
rf_predictions = rf_classifier.predict(X_test_pca)

# Naive Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_pca, y_train)
nb_predictions = nb_classifier.predict(X_test_pca)

# K-NN Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train_pca, y_train)
knn_predictions = knn_classifier.predict(X_test_pca)

# SVM Classifier
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train_pca, y_train)
svm_predictions = svm_classifier.predict(X_test_pca)

# Calculate metrics for each classifier
classifiers = {
    'Decision Tree': dt_predictions,
    'Random Forest': rf_predictions,
    'Naive Bayes': nb_predictions,
    'K-NN': knn_predictions,
    'SVM': svm_predictions
}

for classifier, predictions in classifiers.items():
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted')
    recall = recall_score(y_test, predictions, average='weighted')
    f1 = f1_score(y_test, predictions, average='weighted')
    confusion_mat = confusion_matrix(y_test, predictions)
    roc_auc = roc_auc_score(y_test, svm_classifier.predict_proba(X_test_pca), multi_class='ovr')

    print(f"Metrics for {classifier}:")
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("Confusion Matrix:")
    print(confusion_mat)
    print("ROC-AUC:", roc_auc)
    print("------------------------")


Metrics for Decision Tree:
Accuracy: 0.8109
Precision: 0.8108181647785392
Recall: 0.8109
F1-Score: 0.8100422492059779
Confusion Matrix:
[[736 147   7  33   5   6   3   8  37  18]
 [ 88 810   5  19   5  17   6   5  29  16]
 [  4   4 936  10   2  21   9   5   3   6]
 [ 12  10   9 789  19  28  32  76  16   9]
 [  1   0   4  31 845  49  16   9  16  29]
 [  4   4   3  21  97 819  12   6  22  12]
 [  4   5  11  37  18  25 794  72  12  22]
 [ 12   6   8  45  26  15 135 674  12  67]
 [ 40  19   9   3   9  25   3   1 875  16]
 [ 11  40   3   5  16  12   9   6  67 831]]
ROC-AUC: 0.9954187888888889
------------------------
Metrics for Random Forest:
Accuracy: 0.8914
Precision: 0.8946931511107444
Recall: 0.8914
F1-Score: 0.8908410419985914
Confusion Matrix:
[[798 149   2  20   6   0   2   2  16   5]
 [ 25 919   1  22   4   3   0   1  17   8]
 [  5   1 983   2   0   6   1   1   1   0]
 [  7   8   1 912  21  16   5  22   7   1]
 [  0   1   0  19 936  22   7   2   7   6]
 [  0   1   0  13 114 862   2

In [ ]:
# components of 20

In [22]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Perform PCA with the given component size
pca = PCA(n_components=20)
X_train_pca = pca.fit_transform(kannda_mnist_train_images)
X_test_pca = pca.transform(kannda_mnist_test_images)

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train_pca, y_train)
dt_predictions = dt_classifier.predict(X_test_pca)

# Random Forest Classifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train_pca, y_train)
rf_predictions = rf_classifier.predict(X_test_pca)

# Naive Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_pca, y_train)
nb_predictions = nb_classifier.predict(X_test_pca)

# K-NN Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train_pca, y_train)
knn_predictions = knn_classifier.predict(X_test_pca)

# SVM Classifier
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train_pca, y_train)
svm_predictions = svm_classifier.predict(X_test_pca)

# Calculate metrics for each classifier
classifiers = {
    'Decision Tree': dt_predictions,
    'Random Forest': rf_predictions,
    'Naive Bayes': nb_predictions,
    'K-NN': knn_predictions,
    'SVM': svm_predictions
}

for classifier, predictions in classifiers.items():
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted')
    recall = recall_score(y_test, predictions, average='weighted')
    f1 = f1_score(y_test, predictions, average='weighted')
    confusion_mat = confusion_matrix(y_test, predictions)
    roc_auc = roc_auc_score(y_test, svm_classifier.predict_proba(X_test_pca), multi_class='ovr')

    print(f"Metrics for {classifier}:")
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("Confusion Matrix:")
    print(confusion_mat)
    print("ROC-AUC:", roc_auc)
    print("------------------------")


Metrics for Decision Tree:
Accuracy: 0.8074
Precision: 0.8074550112752786
Recall: 0.8074
F1-Score: 0.8066647682175876
Confusion Matrix:
[[739 129   8  33   9   5   9  10  38  20]
 [ 86 797   9  31   4   7  11   8  29  18]
 [  5   4 933  11   1  20   7   8   5   6]
 [ 18   7  15 783  33  23  18  81   9  13]
 [  0   2   1  45 833  51  10  17  18  23]
 [  3   4   9  24 105 806  10   9  17  13]
 [  8   9   5  49  20  25 796  60   8  20]
 [ 10  10   5  58  27   7 130 673   9  71]
 [ 32  24  15   6  12  14   4   3 872  18]
 [ 10  27   1   5  24   7   6  10  68 842]]
ROC-AUC: 0.996841388888889
------------------------
Metrics for Random Forest:
Accuracy: 0.9023
Precision: 0.905320333382736
Recall: 0.9023
F1-Score: 0.901735959266713
Confusion Matrix:
[[805 143   2  20   6   0   2   2  14   6]
 [ 15 931   1  23   6   1   0   1  14   8]
 [  5   1 980   2   0   7   1   1   1   2]
 [ 12   8   1 924  14  16   4  18   3   0]
 [  0   1   0  20 947  15   3   2   6   6]
 [  0   1   0  12 101 873   4   

In [ ]:
# components=25

In [23]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Perform PCA with the given component size
pca = PCA(n_components=25)
X_train_pca = pca.fit_transform(kannda_mnist_train_images)
X_test_pca = pca.transform(kannda_mnist_test_images)

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train_pca, y_train)
dt_predictions = dt_classifier.predict(X_test_pca)

# Random Forest Classifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train_pca, y_train)
rf_predictions = rf_classifier.predict(X_test_pca)

# Naive Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_pca, y_train)
nb_predictions = nb_classifier.predict(X_test_pca)

# K-NN Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train_pca, y_train)
knn_predictions = knn_classifier.predict(X_test_pca)

# SVM Classifier
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train_pca, y_train)
svm_predictions = svm_classifier.predict(X_test_pca)

# Calculate metrics for each classifier
classifiers = {
    'Decision Tree': dt_predictions,
    'Random Forest': rf_predictions,
    'Naive Bayes': nb_predictions,
    'K-NN': knn_predictions,
    'SVM': svm_predictions
}

for classifier, predictions in classifiers.items():
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted')
    recall = recall_score(y_test, predictions, average='weighted')
    f1 = f1_score(y_test, predictions, average='weighted')
    confusion_mat = confusion_matrix(y_test, predictions)
    roc_auc = roc_auc_score(y_test, svm_classifier.predict_proba(X_test_pca), multi_class='ovr')

    print(f"Metrics for {classifier}:")
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("Confusion Matrix:")
    print(confusion_mat)
    print("ROC-AUC:", roc_auc)
    print("------------------------")


Metrics for Decision Tree:
Accuracy: 0.8047
Precision: 0.8044754208937895
Recall: 0.8047
F1-Score: 0.8037655313152182
Confusion Matrix:
[[742 142   8  32  11   2   3   6  38  16]
 [ 93 793   5  27  13  13   9   3  31  13]
 [  3   3 933  11   3  23   2   8   4  10]
 [ 10  11  17 782  34  26  27  76  11   6]
 [  4   1   2  43 833  50  14  13  15  25]
 [  3   5  13  18 118 801   8   8  17   9]
 [  5   6  10  45  22  19 782  79   7  25]
 [ 15  14   7  50  25   7 138 665  11  68]
 [ 34  12  13  12   8  15   3   2 887  14]
 [ 16  39   8   3  25  11   5   6  58 829]]
ROC-AUC: 0.9970798111111112
------------------------
Metrics for Random Forest:
Accuracy: 0.9051
Precision: 0.9083769769183339
Recall: 0.9051
F1-Score: 0.904468532828274
Confusion Matrix:
[[804 147   2  19   3   0   2   3  15   5]
 [ 13 937   1  21   7   3   0   0  11   7]
 [  2   1 985   3   1   6   1   0   1   0]
 [  8   8   1 934  12  19   2  13   3   0]
 [  0   1   0  18 945  17   4   2   7   6]
 [  0   1   0  11  91 882   4 

In [ ]:
# components=30

In [24]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Perform PCA with the given component size
pca = PCA(n_components=30)
X_train_pca = pca.fit_transform(kannda_mnist_train_images)
X_test_pca = pca.transform(kannda_mnist_test_images)

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train_pca, y_train)
dt_predictions = dt_classifier.predict(X_test_pca)

# Random Forest Classifier
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train_pca, y_train)
rf_predictions = rf_classifier.predict(X_test_pca)

# Naive Bayes Classifier
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_pca, y_train)
nb_predictions = nb_classifier.predict(X_test_pca)

# K-NN Classifier
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train_pca, y_train)
knn_predictions = knn_classifier.predict(X_test_pca)

# SVM Classifier
svm_classifier = SVC(probability=True)
svm_classifier.fit(X_train_pca, y_train)
svm_predictions = svm_classifier.predict(X_test_pca)

# Calculate metrics for each classifier
classifiers = {
    'Decision Tree': dt_predictions,
    'Random Forest': rf_predictions,
    'Naive Bayes': nb_predictions,
    'K-NN': knn_predictions,
    'SVM': svm_predictions
}

for classifier, predictions in classifiers.items():
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average='weighted')
    recall = recall_score(y_test, predictions, average='weighted')
    f1 = f1_score(y_test, predictions, average='weighted')
    confusion_mat = confusion_matrix(y_test, predictions)
    roc_auc = roc_auc_score(y_test, svm_classifier.predict_proba(X_test_pca), multi_class='ovr')

    print(f"Metrics for {classifier}:")
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("Confusion Matrix:")
    print(confusion_mat)
    print("ROC-AUC:", roc_auc)
    print("------------------------")


Metrics for Decision Tree:
Accuracy: 0.8071
Precision: 0.8071004466662444
Recall: 0.8071
F1-Score: 0.8060818327084531
Confusion Matrix:
[[706 158  17  30   6   4   5   5  49  20]
 [ 85 804   4  23   6  12  10   5  36  15]
 [  3   2 933  11   0  28   3   8   5   7]
 [ 16   8  17 792  29  27  29  64  10   8]
 [  3   0   3  32 838  46  12  18  25  23]
 [  8   4   4  21 101 809   7  12  20  14]
 [  3   8   5  32  18  33 809  60   8  24]
 [ 12  15   3  53  26   9 133 679   7  63]
 [ 33  14  15   5   7  24   5   1 880  16]
 [ 18  37   4   6  19  14   6   7  68 821]]
ROC-AUC: 0.9974580666666666
------------------------
Metrics for Random Forest:
Accuracy: 0.9052
Precision: 0.9079827892097027
Recall: 0.9052
F1-Score: 0.9045833526800509
Confusion Matrix:
[[805 142   1  23   2   0   2   2  17   6]
 [ 12 942   1  18   4   3   0   1  11   8]
 [  4   1 981   6   0   5   1   1   1   0]
 [ 11  10   2 931  12  17   5  11   1   0]
 [  0   1   0  20 942  19   2   4   7   5]
 [  0   1   0  10  88 889   3